### DISCUSSION TITLE
Localization

### DISCUSSION THREAD

**Discussion by christianrolle** [RubyMoney/money-rails#663] [Ideas]
Are there thoughts on hooking into the Rails currency localization instead of a static configuration on application level?
Especially in the context of multi-tenant applications or multiple currencies.

**Comment by sunny** [comment]
Currency localization can be done in many ways and usually require a number of different parts (controllers to store a custom currency, selecting the currency in the URL, choosing a default currency per IP, storing the currency in a cookie, storing the favorite currency on a user or tenant, front-end currency picker, storing currency rates in the database, …)

What part do you have in mind?

**Reply by christianrolle** [reply]
Well representing money currently works like:
```
money = Money.new(123)
money.format symbol: true, symbol_after_without_space: false, symbol_position: :after
```
which is deprecated and therefore:
```
money.format format: '%n %u'
```
However in the context of different countries and how money usually is represented across countries which could differ:
`$ 1.23` versus `1,23 €`.
So the money localization is missing with the above examples. I think it would be great to define localized money representations like the Rails I18n date/times:
```
# /config/locales/en-us.yml
---
en-us:
  currency:
    default: "%u %n" # maybe also could be the reasonable default
    concise: "%u%n"

# /config/locales/de.yml
---
de:
  currency:
    default: "%n %u"
    concise: "%n%u"
```
and using it:

```
I18n.locale = 'de'
money.format
# => "1,23 €"
money.format format: :concise
# => "1,23€"
money.format locale: 'en-us'
# => "€ 1.23"
```
If that makes sense.
So I'm looking for a reasonable way to control money representations. I guess having it on top of Rails I18n would make sense?

**Reply by sunny** [reply]
Oh, I see!

For that I use the [rails-i18n](https://gem.wtf/rails-i18n) gem, which configures how numbers and currencies should appear for a lot of locales.

E.g.: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/de-DE.yml#LL153-L160C41

```yml
    currency:
      format:
        delimiter: "."
        format: "%n %u"
        precision: 2
        separator: ","
        significant: false
        strip_insignificant_zeros: false
  ```

**Reply by christianrolle** [reply]
Alright. Then I wonder why the money gem ignores my locale:

```
---
de:
  number:
    currency:
      format:
        format: "%n %u"
```

even though it is wired with I18n:

```
# config/initializers/money.rb
MoneyRails.configure do |config|
  config.locale_backend = :i18n 
end
```

when I do:

```
I18n.locale = :de
Money.new(123).format
# => "€1,23"
```

This just might be an issue but the message `#format` cannot respond to a different kind of named representation, like:
```
Money.new(123).format :concise
# or
Money.new(123).format type: :short
```
It is because we sometimes need to represent the same money in a different way depending on the context.
