### ISSUE TITLE
Validates numericality bug?

### ISSUE THREAD

**Issue by 1v** [RubyMoney/money-rails#479]
```ruby
class Article < ActiveRecord::Base
  monetize :price_cents,
            numericality: { greater_than: 0,
                            less_than_or_equal_to: 21474836 }
...
```
```ruby
    subject { FactoryGirl.build(:article) }

    context '#price' do
      it { is_expected.to monetize(:price) }
      it { subject.price = '21474837'; expect(subject).to_not be_valid }
      it { subject.price = '21474836,01'; expect(subject).to_not be_valid }
      it { subject.price = '21474836'; expect(subject).to be_valid }
      it { subject.price = '0'; expect(subject).to_not be_valid }
      it { subject.price = '-1'; expect(subject).to_not be_valid }
      it { subject.price = '0,01'; expect(subject).to be_valid }
      it { subject.price = '1'; expect(subject).to be_valid }

      let (:article) { FactoryGirl.create(:article, price: '21474836') }

      it 'expect to be valid after create' do
        expect(article).to be_valid
      end
    end
```
All tests passing except last one: Price must be less than or equal to 21474836.
What I'm doing wrong?

`/.rvm/gems/ruby-2.1.0/gems/money-rails-1.6.1`

**Comment by antstorm** [comment]
@1v I'm having zero luck trying to reproduce your error. Can you try the latest version of `money-rails`?

**Comment by 1v** [comment]
@antstorm I've also tried latest version and got same error. Btw Rails version is 4.2.1.

**Comment by antstorm** [comment]
This is quite interesting. Btw, is there a particular reason for using that number? Can you try the same test with something smaller like `1000` and see if that works?

**Comment by 1v** [comment]
It's maximum integer for column. Rails throwing exception if number entered more than that.
I've tried `1000` got same error. After create not passing.

**Comment by antstorm** [comment]
@1v thanks, I'll have a closer look

**Comment by antstorm** [comment]
@1v having zero luck with replicating your issue. Can you please share more details about your setup? Which DB are you running? Schema for that table? Any triggers/constraints? What's the actual error message on the model?

**Comment by 1v** [comment]
Ok I figured out that problem was in locale settings:
```yaml
  number:
    currency:
      format:
        delimiter: '.'
        format: ! '%n %u'
        precision: 2
        separator: ! ','
        significant: false
        strip_insignificant_zeros: false
        unit: €
    format:
      delimiter: .
      precision: 2
      separator: ! ','
      significant: false
      strip_insignificant_zeros: false
```
So I only can stick with my current solution above?
